### ISSUE TITLE
Shared memory

### ISSUE THREAD

**Issue by onet4** [elazar/flystream#5]
Hi,

I have a question. I'm not familiar with streams. 

I'm wondering whether it is possible to store a value in memory from one script and access the value from another script and vice versa. Since the example code in readme appears to deal with memories, is it perhaps possible somehow with this library without installing extra PHP extensions?

**Comment by elazar** [comment]
I'm afraid that your use case is outside the intended scope of this library. If you want to implement interprocess communication with PHP without using non-core extensions, I would suggest looking at the [`reactphp/child-process`](https://reactphp.org/child-process/) library.
